### PR TITLE
a quick analysis of full-length 16S rRNA gene seqeunces with anvi'o

### PR DESCRIPTION
**Pull request by meren**

### CODE REVIEW

**Comment by SamStudio8** [comment]
Hey @meren, this is awesome thanks! Can you add your tutorial as a separate file?

**Comment by nickloman** [comment]
Why separate file?

**Comment by SamStudio8** [comment]
@nickloman just thought it would be nice to separate it out? It's effectively a tutorial in its own right

**Comment by nickloman** [comment]
I know what you mean but it logically follows from the datasets generated in the tutorial. Let's just merge and then if it gets unwieldy split it later?

**Comment by SamStudio8** [comment]
ok!
cheers @meren :)

**Comment by meren** [comment]
Thank you both! :)

**Pull request merged**
